/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import javax.swing.JOptionPane;
import controller.FilmeService;
/**
 *
 * @author rjpsilva
 */
public class CadastrarFilme extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarFilme
     */
    public CadastrarFilme() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private final FilmeService filmeService = FilmeService.getInstance();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classificacaoIndicativa = new javax.swing.ButtonGroup();
        tituloFrame = new javax.swing.JLabel();
        caixaCodFilme = new javax.swing.JTextField();
        labelCodFilme = new javax.swing.JLabel();
        caixaTituloFilme = new javax.swing.JTextField();
        labelTituloFilme = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        botaoSelLivre = new javax.swing.JRadioButton();
        botaoCancelar = new javax.swing.JButton();
        botaoSel10anos = new javax.swing.JRadioButton();
        botaoCadastrar = new javax.swing.JButton();
        labelClassificacao = new javax.swing.JLabel();
        caixaGenero = new javax.swing.JComboBox<>();
        botaoSel12anos = new javax.swing.JRadioButton();
        botaoSel14anos = new javax.swing.JRadioButton();
        botaoSel16anos = new javax.swing.JRadioButton();
        botaoSel18anos = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloFrame.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloFrame.setText("Cadastro de Filme");

        caixaCodFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaCodFilmeActionPerformed(evt);
            }
        });

        labelCodFilme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCodFilme.setText("Código do filme");

        caixaTituloFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaTituloFilmeActionPerformed(evt);
            }
        });

        labelTituloFilme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTituloFilme.setText("Título do filme");

        labelGenero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelGenero.setText("Gênero");

        classificacaoIndicativa.add(botaoSelLivre);
        botaoSelLivre.setText("Livre");

        botaoCancelar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        botaoCancelar.setText("Voltar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        classificacaoIndicativa.add(botaoSel10anos);
        botaoSel10anos.setText("10 anos");
        botaoSel10anos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSel10anosActionPerformed(evt);
            }
        });

        botaoCadastrar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        botaoCadastrar.setText("Salvar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        labelClassificacao.setText("Classificação indicativa");

        caixaGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ação", "Aventura", "Drama", "Ficção Ciêntífica", "Romance", "Terror" }));
        caixaGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaGeneroActionPerformed(evt);
            }
        });

        classificacaoIndicativa.add(botaoSel12anos);
        botaoSel12anos.setText("12 anos");
        botaoSel12anos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSel12anosActionPerformed(evt);
            }
        });

        classificacaoIndicativa.add(botaoSel14anos);
        botaoSel14anos.setText("14 anos");
        botaoSel14anos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSel14anosActionPerformed(evt);
            }
        });

        classificacaoIndicativa.add(botaoSel16anos);
        botaoSel16anos.setText("16 anos");
        botaoSel16anos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSel16anosActionPerformed(evt);
            }
        });

        classificacaoIndicativa.add(botaoSel18anos);
        botaoSel18anos.setText("18 anos");
        botaoSel18anos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSel18anosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelClassificacao)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(tituloFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(caixaTituloFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTituloFilme)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caixaCodFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCodFilme))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelGenero)
                            .addComponent(caixaGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoSelLivre)
                        .addGap(18, 18, 18)
                        .addComponent(botaoSel10anos)
                        .addGap(18, 18, 18)
                        .addComponent(botaoSel12anos)
                        .addGap(37, 37, 37)
                        .addComponent(botaoSel14anos)
                        .addGap(18, 18, 18)
                        .addComponent(botaoSel16anos)
                        .addGap(18, 18, 18)
                        .addComponent(botaoSel18anos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(labelTituloFilme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixaTituloFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodFilme)
                    .addComponent(labelGenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaCodFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caixaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelClassificacao, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoSelLivre)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaoSel10anos)
                        .addComponent(botaoSel12anos)
                        .addComponent(botaoSel14anos)
                        .addComponent(botaoSel16anos)
                        .addComponent(botaoSel18anos)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caixaCodFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaCodFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaCodFilmeActionPerformed

    private void caixaTituloFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaTituloFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaTituloFilmeActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        // 1. Instancia a nova tela (Cria o objeto da janela de destino)
        MostrarFilmes proximaTela = new MostrarFilmes();

        // 2. Faz a nova tela aparecer
        proximaTela.setVisible(true);

        // 3. Fecha a tela atual (libera memória)
        this.dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoSel10anosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSel10anosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSel10anosActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        // 1. Validação do TÍTULO DO FILME
        if (caixaTituloFilme.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, informe o Título do filme.");
            caixaTituloFilme.requestFocus(); // Foco no campo título
            return;
        }

        // 2. Validação do CÓDIGO DO FILME
        if (caixaCodFilme.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, informe o Código do filme.");
            caixaCodFilme.requestFocus();
            return;
        }

        // 3. Validação da CLASSIFICAÇÃO (Radio Buttons)
        /* Truque Ninja: Em vez de verificar botão por botão (!Livre && !10anos && !12anos...),
           nós perguntamos para o GRUPO se existe alguma seleção feita.
           Se getSelection() retornar 'null', significa que nenhum botão do grupo foi marcado.
        */
        if (classificacaoIndicativa.getSelection() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione a Classificação Indicativa.");
            return;
        }

        // 4. Validação do GÊNERO (ComboBox)
        /* Geralmente a ComboBox já vem com o primeiro item ("Ação") selecionado.
           Mas é uma boa prática garantir que o objeto selecionado não é nulo.
        */
        if (caixaGenero.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um Gênero.");
            caixaGenero.requestFocus();
            return;
        }

        int codigo;
        try {
            codigo = Integer.parseInt(caixaCodFilme.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O código do filme deve ser numérico.");
            caixaCodFilme.requestFocus();
            return;
        }

        String genero = caixaGenero.getSelectedItem().toString();
        int classificacao = obterClassificacaoSelecionada();

        try {
            filmeService.cadastrarFilme(codigo, caixaTituloFilme.getText().trim(), genero, classificacao);
            JOptionPane.showMessageDialog(this, "Filme cadastrado com sucesso!");
            limparCampos();
        } catch (IllegalArgumentException | IllegalStateException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoSel12anosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSel12anosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSel12anosActionPerformed

    private void botaoSel14anosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSel14anosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSel14anosActionPerformed

    private void botaoSel16anosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSel16anosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSel16anosActionPerformed

    private void botaoSel18anosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSel18anosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSel18anosActionPerformed

    private void caixaGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaGeneroActionPerformed
    private int obterClassificacaoSelecionada() {
        if (botaoSelLivre.isSelected()) {
            return 0;
        }
        if (botaoSel10anos.isSelected()) {
            return 10;
        }
        if (botaoSel12anos.isSelected()) {
            return 12;
        }
        if (botaoSel14anos.isSelected()) {
            return 14;
        }
        if (botaoSel16anos.isSelected()) {
            return 16;
        }
        return 18;
    }

    private void limparCampos() {
        caixaTituloFilme.setText("");
        caixaCodFilme.setText("");
        classificacaoIndicativa.clearSelection();
        caixaGenero.setSelectedIndex(0);
        caixaTituloFilme.requestFocus();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JRadioButton botaoSel10anos;
    private javax.swing.JRadioButton botaoSel12anos;
    private javax.swing.JRadioButton botaoSel14anos;
    private javax.swing.JRadioButton botaoSel16anos;
    private javax.swing.JRadioButton botaoSel18anos;
    private javax.swing.JRadioButton botaoSelLivre;
    private javax.swing.JTextField caixaCodFilme;
    private javax.swing.JComboBox<String> caixaGenero;
    private javax.swing.JTextField caixaTituloFilme;
    private javax.swing.ButtonGroup classificacaoIndicativa;
    private javax.swing.JLabel labelClassificacao;
    private javax.swing.JLabel labelCodFilme;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelTituloFilme;
    private javax.swing.JLabel tituloFrame;
    // End of variables declaration//GEN-END:variables
}
