/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import javax.swing.JOptionPane;

import controller.UsuarioService;
import model.Usuario;
/**
 *
 * @author rjpsilva
 */
public class CadastrarUsuario extends javax.swing.JFrame {
    private final UsuarioService usuarioService;
    private boolean emModoEdicao = false;
    private Usuario usuarioEmEdicao;
    /**
     * Creates new form CadastrarUsuario1
     */
    public CadastrarUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuarioService = UsuarioService.getInstance();
        configurarModoCadastro();
    }

    public CadastrarUsuario(Usuario usuarioParaEdicao) {
        this();
        this.emModoEdicao = true;
        this.usuarioEmEdicao = usuarioParaEdicao;
        preencherCampos(usuarioParaEdicao);
        configurarModoEdicao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoUsuario = new javax.swing.ButtonGroup();
        labelTelefone = new javax.swing.JLabel();
        caixaEndereco = new javax.swing.JTextField();
        botaoSelFunc = new javax.swing.JRadioButton();
        botaoCancelar = new javax.swing.JButton();
        botaoSelCli = new javax.swing.JRadioButton();
        botaoCadastrar = new javax.swing.JButton();
        labelTipoUsu = new javax.swing.JLabel();
        labelEndereco = new javax.swing.JLabel();
        tituloFrame = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        caixaNome = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        caixaCpf = new javax.swing.JFormattedTextField();
        caixaTel = new javax.swing.JFormattedTextField();
        labelEditar = new javax.swing.JLabel();
        botaoSalvarEdicao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTelefone.setText("Telefone");

        caixaEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaEnderecoActionPerformed(evt);
            }
        });

        tipoUsuario.add(botaoSelFunc);
        botaoSelFunc.setText("Funcionário");

        botaoCancelar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        botaoCancelar.setText("Voltar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        tipoUsuario.add(botaoSelCli);
        botaoSelCli.setText("Cliente");
        botaoSelCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSelCliActionPerformed(evt);
            }
        });

        botaoCadastrar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        botaoCadastrar.setText("Salvar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        labelTipoUsu.setText("Tipo de usuário");

        labelEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEndereco.setText("Endereço");

        tituloFrame.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloFrame.setText("Cadastro de Usuário");

        labelCpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCpf.setText("CPF");

        caixaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaNomeActionPerformed(evt);
            }
        });

        labelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNome.setText("Nome");

        try {
            caixaCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            caixaTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        labelEditar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEditar.setText("Editar Usuário");

        botaoSalvarEdicao.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        botaoSalvarEdicao.setText("Salvar");
        botaoSalvarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarEdicaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(caixaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNome)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCpf)
                                    .addComponent(caixaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEndereco))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelTelefone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelTipoUsu))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(caixaTel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(botaoSelFunc)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoSelCli))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoSalvarEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(caixaEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpf)
                    .addComponent(labelTelefone)
                    .addComponent(labelTipoUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(caixaTel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(botaoSelFunc)
                        .addComponent(botaoSelCli))
                    .addComponent(caixaCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixaEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSalvarEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caixaEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaEnderecoActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        // 1. Instancia a nova tela (Cria o objeto da janela de destino)
        MostrarUsuarios proximaTela = new MostrarUsuarios();

        // 2. Faz a nova tela aparecer
        proximaTela.setVisible(true);

        // 3. Fecha a tela atual (libera memória)
        this.dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        if (emModoEdicao) {
            return;
        }

        if (!validarCampos()) {
            return;
        }

        String nome = caixaNome.getText().trim();
        String cpf = caixaCpf.getText().trim();
        String telefone = caixaTel.getText().trim();
        String endereco = caixaEndereco.getText().trim();
        String tipo = botaoSelFunc.isSelected() ? "Funcionario" : "Cliente";

        try {
            usuarioService.cadastrarUsuario(nome, cpf, telefone, endereco, tipo);
            JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!");
            limparCampos();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "CPF duplicado", JOptionPane.WARNING_MESSAGE);
            caixaCpf.requestFocus();
        } catch (IllegalStateException e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar usuário: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private boolean validarCampos() {
        // 1. Validação do NOME (Campo de texto normal)
        if (caixaNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe o Nome.");
            caixaNome.requestFocus();
            return false;
        }

        // 2. Validação do CPF (Campo Formatado)
        // Removemos pontos, traços e espaços para ver se sobrou algum número
        String cpfSemFormatacao = caixaCpf.getText().replace(".", "").replace("-", "").replace(" ", "");
        if (cpfSemFormatacao.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe o CPF.");
            caixaCpf.requestFocus();
            return false;
        }

        // 3. Validação do TELEFONE (Campo Formatado)
        // Removemos parênteses, traços e espaços
        String telSemFormatacao = caixaTel.getText().replace("(", "").replace(")", "").replace("-", "").replace(" ", "");
        if (telSemFormatacao.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe o Telefone.");
            caixaTel.requestFocus();
            return false;
        }

        // 4. Validação dos RADIO BUTTONS (Tipo de Usuário)
        // Verifica se nem o funcionário nem o cliente estão marcados
        if (!botaoSelFunc.isSelected() && !botaoSelCli.isSelected()) {
            JOptionPane.showMessageDialog(this, "Selecione o Tipo de Usuário (Funcionário ou Cliente).");
            return false;
        }

        // 5. Validação do ENDEREÇO
        if (caixaEndereco.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe o Endereço.");
            caixaEndereco.requestFocus();
            return false;
        }
        return true;
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    // Método auxiliar para limpar a tela após cadastrar
    private void limparCampos() {
        caixaNome.setText("");
        caixaCpf.setText("");
        caixaCpf.setValue(null); // Reseta a máscara
        caixaTel.setText("");
        caixaTel.setValue(null);
        caixaEndereco.setText("");
        tipoUsuario.clearSelection(); // Limpa os radio buttons
        caixaNome.requestFocus();
    }
    
    private void caixaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaNomeActionPerformed

    private void botaoSalvarEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarEdicaoActionPerformed
        if (!emModoEdicao || usuarioEmEdicao == null) {
            return;
        }

        if (!validarCampos()) {
            return;
        }

        String nome = caixaNome.getText().trim();
        String cpf = caixaCpf.getText().trim();
        String telefone = caixaTel.getText().trim();
        String endereco = caixaEndereco.getText().trim();
        String tipo = botaoSelFunc.isSelected() ? "Funcionario" : "Cliente";

        try {
            usuarioService.atualizarUsuario(usuarioEmEdicao.getCpf(), nome, cpf, telefone, endereco, tipo);
            JOptionPane.showMessageDialog(this, "Usuário atualizado com sucesso!");
            abrirListaUsuarios();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro na atualização", JOptionPane.WARNING_MESSAGE);
            caixaCpf.requestFocus();
        } catch (IllegalStateException e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar usuário: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoSalvarEdicaoActionPerformed

    private void botaoSelCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSelCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSelCliActionPerformed

    private void preencherCampos(Usuario usuario) {
        caixaNome.setText(usuario.getNome());
        caixaCpf.setText(usuario.getCpf());
        caixaTel.setText(usuario.getTelefone());
        caixaEndereco.setText(usuario.getEndereco());

        String tipo = usuarioService.obterTipoTextual(usuario);
        if (tipo.equalsIgnoreCase("Funcionario")) {
            botaoSelFunc.setSelected(true);
        } else {
            botaoSelCli.setSelected(true);
        }
    }

    private void configurarModoCadastro() {
        emModoEdicao = false;
        tituloFrame.setVisible(true);
        labelEditar.setVisible(false);
        botaoCadastrar.setVisible(true);
        botaoSalvarEdicao.setVisible(false);
    }

    private void configurarModoEdicao() {
        tituloFrame.setVisible(false);
        labelEditar.setVisible(true);
        botaoCadastrar.setVisible(false);
        botaoSalvarEdicao.setVisible(true);
    }

    private void abrirListaUsuarios() {
        MostrarUsuarios proximaTela = new MostrarUsuarios();
        proximaTela.setVisible(true);
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoSalvarEdicao;
    private javax.swing.JRadioButton botaoSelCli;
    private javax.swing.JRadioButton botaoSelFunc;
    private javax.swing.JFormattedTextField caixaCpf;
    private javax.swing.JTextField caixaEndereco;
    private javax.swing.JTextField caixaNome;
    private javax.swing.JFormattedTextField caixaTel;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelEditar;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTipoUsu;
    private javax.swing.ButtonGroup tipoUsuario;
    private javax.swing.JLabel tituloFrame;
    // End of variables declaration//GEN-END:variables
}
