/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import controller.UsuarioService;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.Usuario;

/**
 *
 * @author rjpsilva
 */
public class MostrarUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form MostrarUsuarios
     */
    public MostrarUsuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        configurarTabela();
        configurarListeners();
        carregarUsuariosNaTabela(usuarioService.getUsuarios());
        atualizarEstadoAcoes();
    }
    
    private final UsuarioService usuarioService = UsuarioService.getInstance();
    private DefaultTableModel modeloTabela;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloFrame = new javax.swing.JLabel();
        barraPesquisa = new javax.swing.JTextField();
        botaoPesquisar = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        scrollUsuarios = new javax.swing.JScrollPane();
        tabelaUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloFrame.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloFrame.setText("Usuários");

        barraPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraPesquisaActionPerformed(evt);
            }
        });

        botaoPesquisar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        botaoPesquisar.setText("Pesquisar");

        botaoCadastrar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        botaoCadastrar.setText("Cadastrar Novo");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        botaoVoltar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoEditar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        botaoEditar.setText("Editar Usuário");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        scrollUsuarios.setToolTipText("");
        scrollUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        scrollUsuarios.setViewportView(tabelaUsuarios);
        tabelaUsuarios.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(botaoVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(botaoCadastrar)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(botaoEditar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrollUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(barraPesquisa)))))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar)
                    .addComponent(botaoCadastrar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barraPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(scrollUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoEditar)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraPesquisaActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // 1. Instancia a nova tela (Cria o objeto da janela de destino)
        MenuPrincipal proximaTela = new MenuPrincipal();

        // 2. Faz a nova tela aparecer
        proximaTela.setVisible(true);

        // 3. Fecha a tela atual (libera memória)
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        // 1. Instancia a nova tela (Cria o objeto da janela de destino)
        CadastrarUsuario proximaTela = new CadastrarUsuario();

        // 2. Faz a nova tela aparecer
        proximaTela.setVisible(true);

        // 3. Fecha a tela atual (libera memória)
        this.dispose();
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void configurarTabela() {
        modeloTabela = new DefaultTableModel(
                new Object[]{"CPF", "Nome", "Telefone", "Endereço"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tabelaUsuarios.setModel(modeloTabela);
        tabelaUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        
        tabelaUsuarios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        var colModel = tabelaUsuarios.getColumnModel();

        colModel.getColumn(0).setPreferredWidth(100);   // CPF
        colModel.getColumn(1).setPreferredWidth(230);  // Nome
        colModel.getColumn(2).setPreferredWidth(100);  // Telefone
        colModel.getColumn(3).setPreferredWidth(230);  // Endereço
    }

    private void configurarListeners() {
        botaoPesquisar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pesquisarUsuarios();
            }
        });

        botaoEditar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                editarUsuarioSelecionado();
            }
        });

        barraPesquisa.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                tratarAlteracaoPesquisa();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                tratarAlteracaoPesquisa();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                tratarAlteracaoPesquisa();
            }
        });

        tabelaUsuarios.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    atualizarEstadoAcoes();
                }
            }
        });
    }

    private void tratarAlteracaoPesquisa() {
        if (barraPesquisa.getText().trim().isEmpty()) {
            carregarUsuariosNaTabela(usuarioService.getUsuarios());
        }
        atualizarEstadoAcoes();
    }

    private void carregarUsuariosNaTabela(List<Usuario> usuarios) {
        modeloTabela.setRowCount(0);

        for (Usuario usuario : usuarios) {
            modeloTabela.addRow(new Object[]{
                normalizarCpfParaExibicao(usuario.getCpf()),
                valorSeguro(usuario.getNome()),
                valorSeguro(usuario.getTelefone()),
                valorSeguro(usuario.getEndereco())
            });
        }
    }

    private void pesquisarUsuarios() {
        String termo = barraPesquisa.getText().trim();

        if (termo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe um CPF ou nome para pesquisar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String termoMinusculo = termo.toLowerCase();
        String termoCpf = normalizarDocumento(termo);

        List<Usuario> encontrados = usuarioService.getUsuarios().stream()
                .filter(usuario -> correspondePesquisa(usuario, termoMinusculo, termoCpf))
                .collect(Collectors.toList());

        if (encontrados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum usuário encontrado.", "Pesquisa", JOptionPane.INFORMATION_MESSAGE);
        }

        carregarUsuariosNaTabela(encontrados);
    }

    private boolean correspondePesquisa(Usuario usuario, String termoMinusculo, String termoCpf) {
        boolean nomeCorresponde = usuario.getNome() != null && usuario.getNome().toLowerCase().contains(termoMinusculo);
        boolean cpfCorresponde = !termoCpf.isEmpty() && normalizarDocumento(usuario.getCpf()).contains(termoCpf);

        return nomeCorresponde || cpfCorresponde;
    }

    private void editarUsuarioSelecionado() {
        int linhaSelecionada = tabelaUsuarios.getSelectedRow();

        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um usuário para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String cpf = (String) modeloTabela.getValueAt(linhaSelecionada, 0);

        Usuario usuarioSelecionado = usuarioService.buscarUsuarioPorCpf(cpf);

        if (usuarioSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Usuário não encontrado para edição.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        CadastrarUsuario telaEdicao = new CadastrarUsuario(usuarioSelecionado);
        telaEdicao.setVisible(true);
        this.dispose();
    }

    private void limparFiltro() {
        barraPesquisa.setText("");
        tabelaUsuarios.clearSelection();
    }

    private void atualizarEstadoAcoes() {
        boolean temSelecao = tabelaUsuarios.getSelectedRow() >= 0;
        boolean temTextoPesquisa = !barraPesquisa.getText().trim().isEmpty();

        botaoEditar.setEnabled(temSelecao);
        botaoPesquisar.setEnabled(temTextoPesquisa);
    }

    private String valorSeguro(String valor) {
        return valor == null ? "" : valor.trim();
    }

    private String normalizarDocumento(String valor) {
        return valor.replaceAll("[^0-9]", "");
    }

    private String normalizarCpfParaExibicao(String cpf) {
        return valorSeguro(cpf);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraPesquisa;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JScrollPane scrollUsuarios;
    private javax.swing.JTable tabelaUsuarios;
    private javax.swing.JLabel tituloFrame;
    // End of variables declaration//GEN-END:variables
}
