/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

/**
 *
 * @author rjpsilva
 */
public class MostrarFilmes extends javax.swing.JFrame {

    /**
     * Creates new form MostrarFilmes
     */
    public MostrarFilmes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadastrar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        caixaPesquisar = new javax.swing.JTextField();
        painelFilmes = new java.awt.ScrollPane();
        labelCpf = new javax.swing.JLabel();
        botaoPesquisar = new javax.swing.JButton();
        botaoAlugar = new javax.swing.JButton();
        botaoDevolver = new javax.swing.JButton();
        tituloFrame = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoCadastrar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        botaoCadastrar.setText("Cadastrar Novo");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        botaoExcluir.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        botaoExcluir.setText("Excluir Filme");

        caixaPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaPesquisarActionPerformed(evt);
            }
        });

        labelCpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCpf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCpf.setText("CPF do Cliente");

        botaoPesquisar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        botaoPesquisar.setText("Pesquisar");

        botaoAlugar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        botaoAlugar.setText("Alugar Filme");

        botaoDevolver.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        botaoDevolver.setText("Devolver Filme");

        tituloFrame.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloFrame.setText("Filmes");

        botaoVoltar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(botaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botaoVoltar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(caixaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(tituloFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(botaoCadastrar)
                        .addGap(41, 41, 41))))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFormattedTextField1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(painelFilmes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(botaoAlugar)
                            .addGap(56, 56, 56)
                            .addComponent(botaoDevolver)
                            .addGap(48, 48, 48)
                            .addComponent(botaoExcluir))
                        .addComponent(labelCpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar)
                    .addComponent(botaoCadastrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(painelFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoExcluir)
                    .addComponent(botaoAlugar)
                    .addComponent(botaoDevolver))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        // 1. Instancia a nova tela (Cria o objeto da janela de destino)
        CadastrarFilme proximaTela = new CadastrarFilme();

        // 2. Faz a nova tela aparecer
        proximaTela.setVisible(true);

        // 3. Fecha a tela atual (libera memória)
        this.dispose();
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void caixaPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaPesquisarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // 1. Instancia a nova tela (Cria o objeto da janela de destino)
        MenuPrincipal proximaTela = new MenuPrincipal();

        // 2. Faz a nova tela aparecer
        proximaTela.setVisible(true);

        // 3. Fecha a tela atual (libera memória)
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlugar;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoDevolver;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField caixaPesquisar;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel labelCpf;
    private java.awt.ScrollPane painelFilmes;
    private javax.swing.JLabel tituloFrame;
    // End of variables declaration//GEN-END:variables
}
